CREATE DATABASE Pessoa;
USE Pessoa;

CREATE TABLE Pessoas (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
cpf VARCHAR(14) NOT NULL,
telefone VARCHAR(15) NOT NULL
);

SELECT * from Pessoas